.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. aych_qt test_aych_qt
clean: FORCE
	$(MAKE) -C .. aych_qt_clean test_aych_qt_clean
check: FORCE
	$(MAKE) -C .. test_aych_qt_check
aych-qt aych-qt.exe: FORCE
	 $(MAKE) -C .. aych_qt
